ALTER TABLE public.assignments REPLICA IDENTITY FULL;
ALTER TABLE public.disasters REPLICA IDENTITY FULL;
ALTER TABLE public.teams REPLICA IDENTITY FULL;
ALTER TABLE public.messages REPLICA IDENTITY FULL;
ALTER TABLE public.notifications REPLICA IDENTITY FULL;